### ISSUE TITLE
The links of adminbar have error on multiple subdomains.

### ISSUE THREAD

**Issue by ghost** [wbrowar/craft-admin-bar#24]
Like I said, The links of adminbar have error on multiple subdomains. 
eg: 
    My craftcms have tow domains. 
       The front end. `www.example.com`
       The control panel. `admin.example.com`
    If I click the Dashboard button on the front end, That will open `www.example.com/dashboard`, Because the href not have domain in `/src/templates/bar.twig`, Just a URI.
Could you fix it? Thanks,

**Comment by wbrowar** [comment]
Hi, @hackerstory. I'm sorry to let this issue sit for so long. I think I have address it in the upcoming Admin Bar 4.0 release. Instead of using the [`url()` Twig function](https://craftcms.com/docs/4.x/dev/functions.html#url), I changed all CP URLs to use the [`cpUrl() function](https://craftcms.com/docs/4.x/dev/functions.html#cpurl). This should take into account the differences in your domain settings.

If you are still running into this issue after upgrading to Admin Bar 4, please re-open this issue and let me know that you are still having a problem with it.
